#!/usr/bin/env bash

REPO=$(dirname $(readlink -f $0))

# Alacritty
cp -f "$REPO/alacritty/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"

# ZSH
cp -f "$REPO/zsh/.zshrc" "$HOME/.zshrc"
cp -f "$REPO/zsh/.p10k.zsh" "$HOME/.p10k.zsh"
